### ISSUE TITLE
请问如何轴国内的CDN加速

### ISSUE THREAD

**Issue by seraluce** [Mxmilu666/cloudflare-dockerhub-proxy#1]
## 提问
我用的域名是国内的备案域名，在cloudflare解析的dns，绑定的workers和pages。  
国内还有已经备案的域名，请问怎么给他套阿里云的cdn进行加速？   

## 条件
* 两个备案域名
* 阿里云CDN和DCDN都可以
* 国外平台购买的域名也有
## 总结
如何访问国内的域名进行CDN加速workers和pages绑定的域名  
顺便问一嘴还有vercel和netfily的域名
，有知道的麻烦回答一下，谢谢！

**Comment by Mxmilu666** [comment]
你可以直接使用 `阿里云DCDN` 加速，在 `源站` 写你 `worker 的域名` 然后 host 也写 `worker 的域名` 即可
但是 `阿里云DCDN` 有没有海外节点我就不知道了

**Comment by Glendia** [comment]
> 你可以直接使用 `阿里云DCDN` 加速，在 `源站` 写你 `worker 的域名` 然后 host 也写 `worker 的域名` 即可
> 但是 `阿里云DCDN` 有没有海外节点我就不知道了

请问'workers'域名是自定义域名还是系统给出的域名

**Comment by seraluce** [comment]
* 请问`workers`域名是自定义域名还是`cloudflare`给出的域名或者说都可以  
* 我的想法是`workers/pages`项目绑定自定义域名并开启`CDN/DCDN`   然后阿里云的cdn再套一层，但是好像失效了，不知道什么原因

**Comment by Mxmilu666** [comment]
> * 请问`workers`域名是自定义域名还是`cloudflare`给出的域名或者说都可以  
> * 我的想法是`workers/pages`项目绑定自定义域名并开启`CDN/DCDN`   然后阿里云的cdn再套一层，但是好像失效了，不知道什么原因
> 

都可以的，但是回源host要写cf的域名
